config/routes.rb
Rails.application.routes.draw do
  resources :locations
  get "welcome/index"
  devise_for :users
  mount Sidekiq::Web => "/sidekiq" if defined?(Sidekiq) # monitoring console
  root "welcome#index", as: :root
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id               :bigint           not null, primary key
#  address_line_one :string
#  address_line_two :string
#  city             :string
#  cleaner_title    :string
#  client_title     :string
#  details          :text
#  state            :string
#  zip              :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  user_id          :bigint           not null
#
# Indexes
#
#  index_locations_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Location < ApplicationRecord
  belongs_to :client, class_name: "User"

  # scope :utah, -> { where(state: "UT") }
  # before_save :upcasing_state

  # private

  # def upcasing_state
  #   self.state = state.upcase
  # end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  user_type              :integer          default("cleaner")
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  self.inheritance_column = :_type_disabled
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :locations, class_name: "Location", foreign_key: :client_id, dependent: :destroy
  # inverse_of: "client"
  enum user_type: { cleaner: 0, client: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # http_basic_authenticate_with name: "dhh", password: "secret", except: :index
  # before_action :authenticate_user!
end

app/controllers/concerns/basic_auth.rb
module BasicAuth
  extend ActiveSupport::Concern

  included do
    before_action :require_basic_auth
  end

  private

  def require_basic_auth
    expected_username = ENV.fetch("BASIC_AUTH_USERNAME", nil)
    expected_password = ENV.fetch("BASIC_AUTH_PASSWORD", nil)
    return true if expected_username.blank? || expected_password.blank?

    authenticate_or_request_with_http_basic do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(username, expected_username) & \
        ActiveSupport::SecurityUtils.secure_compare(password, expected_password)
    end
  end
end

app/controllers/home_controller.rb
# Renders the home page.
class HomeController < ApplicationController
  def index
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[show edit update destroy]

  # GET /locations
  def index
    @locations = Location.all
  end

  # GET /locations/1
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  def create
    @location = Location.new(location_params)
    # @location = current_user.locations.new(location_params)

    if @location.save
      redirect_to @location, notice: "Location was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /locations/1
  def update
    if @location.update(location_params)
      redirect_to @location, notice: "Location was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /locations/1
  def destroy
    @location.destroy
    redirect_to locations_url, notice: "Location was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_location
    @location = Location.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def location_params
    params.require(:location).permit(
      :address_line_one,
      :address_line_two,
      :city,
      :state,
      :zip,
      :client_title,
      :cleaner_title,
      :details,
      :client_id
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  # Used to achieve nested layouts without content_for. This helper relies on
  # Rails internals, so beware that it make break with future major versions
  # of Rails. Inspired by http://stackoverflow.com/a/18214036
  #
  # Usage: For example, suppose "child" layout extends "parent" layout.
  # Use <%= yield %> as you would with non-nested layouts, as usual. Then on
  # the very last line of layouts/child.html.erb, include this:
  #
  #     <% parent_layout "parent" %>
  #
  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer) # rubocop:disable Rails/HelperInstanceVariable
    output = render(template: "layouts/#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<% provide(:title, "Home") %>


 <%= current_user ? current_user.attributes : "hjellow" %>

app/views/layouts/application.html.erb
<%# The "application" layout is the default layout. It extends "base"  %>
<%# to include things like header, footer, and alerts that are common  %>
<%# to most (but not all) views.                                       %>

<main class="container">
  <%= render("shared/flash") %>
  <%= yield %>
</main>

<% parent_layout "base" %>

app/views/layouts/base.html.erb
<%# The "base" layout contains boilerplate common to *all* views. %>

<!DOCTYPE html>
<html>
  <head>

    <title>
      <%= "#{strip_tags(yield(:title))} – " if content_for?(:title) %>
      Schedule 
    </title>
    <%# Specifies the default name of home screen bookmark in iOS %>
    <meta name="apple-mobile-web-app-title" content="app">


    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= yield(:head) %>  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location) do |form| %>
  <% if location.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :address_line_one, style: "display: block" %>
    <%= form.text_field :address_line_one %>
  </div>

  <div>
    <%= form.label :address_line_two, style: "display: block" %>
    <%= form.text_field :address_line_two %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :zip, style: "display: block" %>
    <%= form.text_field :zip %>
  </div>

  <div>
    <%= form.label :client_title, style: "display: block" %>
    <%= form.text_field :client_title %>
  </div>

  <div>
    <%= form.label :cleaner_title, style: "display: block" %>
    <%= form.text_field :cleaner_title %>
  </div>

  <div>
    <%= form.label :details, style: "display: block" %>
    <%= form.text_area :details %>
  </div>

  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.text_field :client_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/_location.html.erb
<div id="<%= dom_id location %>">
  <p>
    <strong>Address line one:</strong>
    <%= location.address_line_one %>
  </p>

  <p>
    <strong>Address line two:</strong>
    <%= location.address_line_two %>
  </p>

  <p>
    <strong>City:</strong>
    <%= location.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= location.state %>
  </p>

  <p>
    <strong>Zip:</strong>
    <%= location.zip %>
  </p>

  <p>
    <strong>Client title:</strong>
    <%= location.client_title %>
  </p>

  <p>
    <strong>Cleaner title:</strong>
    <%= location.cleaner_title %>
  </p>

  <p>
    <strong>Details:</strong>
    <%= location.details %>
  </p>

  <p>
    <strong>Client:</strong>
    <%= location.client_id %>
  </p>

</div>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render "form", location: @location %>

<br>

<div>
  <%= link_to "Show this location", @location %> |
  <%= link_to "Back to locations", locations_path %>
</div>

app/views/locations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Locations</h1>

<div id="locations">
  <% @locations.each do |location| %>
    <%= render location %>
    <p>
      <%= link_to "Show this location", location %>
    </p>
  <% end %>
</div>

<%= link_to "New location", new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render "form", location: @location %>

<br>

<div>
  <%= link_to "Back to locations", locations_path %>
</div>

app/views/locations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @location %>

<div>
  <%= link_to "Edit this location", edit_location_path(@location) %> |
  <%= link_to "Back to locations", locations_path %>

  <%= button_to "Destroy this location", @location, method: :delete %>
</div>

app/views/shared/_flash.html.erb
<%# Notice %>
<% if flash[:notice].present? %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<%# Alert %>
<% if flash[:alert].present? %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>

app/views/welcome/index.html.erb
<% days = (Date.today.beginning_of_week - 14.days..Date.today.beginning_of_week - 1.day).to_a %>

<div class="grid grid-cols-7 gap-4">
  <% days.each do |day| %>
    <div class="">
      <button class="border-hidden">
        <%= Date::ABBR_DAYNAMES[day.wday] %>

        <p><%= day.day %></p>
      </button>
    </div>
<% end %>
<button data-controller="fetch-locations" data-action="click->fetch-locations#fetch" >fetch</button>

</div>

  
<div class="mt-5">
  <form accept-charset="UTF-8">
    Time in

      <input type="time" name="clock_in" id="clock_in" />
      Time out

      <input type="time" name="clock_out" id="clock_out" />
    </form>


</div>

app/views/welcome/index.html.haml
-days = (Date.today.beginning_of_week - 14.days .. Date.today.beginning_of_week - 1.day).to_a%
%div{class:"grid grid-cols-7 gap-4"}
- days.each do |day| 
  =link_to class="border-hidden" do
    = Date::ABBR_DAYNAMES[day.wday]
      = day.day 